name: Run Apartment Scraper

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - p2

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        working-directory: ./server  # <-- Change to server directory
        run: npm ci

      - name: Run Scraper
        working-directory: ./server  # <-- Run from server directory
        run: npm run scrape:newapartments
        env:
          NODE_ENV: production